services:
  - type: web
    name: travel-guide-backend
    env: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MURF_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
