services:
  - type: web
    name: tourist-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MURF_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
